<a href="https://colab.research.google.com/github/anarchy373/BTECH-Python-Projects/blob/main/Python_Module_3_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv('horse_racing.csv')

In [ ]:
df.head()

,Dato,Track,Race Number,Distance,Surface,Prize money,Starting position,Jockey,Jockey weight,Country,...,TrainerName,Race time,Path,Final place,FGrating,Odds,RaceType,HorseId,JockeyId,TrainerID
0,03.09.2017,Sha Tin,10,1400,Gress,1310000,6,K C Leung,52,Sverige,...,CH Yip,8338,2,9,110,22,Handicap,1736,8656,6687
1,16.09.2017,Sha Tin,10,1400,Gress,1310000,14,C Y Ho,52,Sverige,...,CH Yip,8156,3,4,124,48,Handicap,1736,8659,6687
2,14.10.2017,Sha Tin,10,1400,Gress,1310000,8,C Y Ho,52,Sverige,...,CH Yip,8236,1,6,118,11,Handicap,1736,8659,6687
3,11.11.2017,Sha Tin,9,1600,Gress,1310000,13,Brett Prebble,54,Sverige,...,CH Yip,9653,0,8,107,11,Handicap,1736,8453,6687
4,26.11.2017,Sha Tin,9,1600,Gress,1310000,9,C Y Ho,52,Sverige,...,CH Yip,9417,0,3,123,40,Handicap,1736,8659,6687

In [ ]:
# Question 1: Of all the rows in the data set what was the average weight of a jockey? Weights are listed in kilograms. Round to two decimal places.

round(df['Jockey weight'].mean(), 2)

55.87

In [ ]:
# Question 2: What was the average race time for jockey Brett Prebble? Round to two decimal places.

# Define the jockey's name
jockey_name = 'Brett Prebble'
# Filter the Dataframe for the specific jockey
jockey_data = df[df['Jockey'] == jockey_name]

# Calculate the average race time for the jockey
average_race_time = jockey_data['Race time'].mean()

# Round the result to two decimal places
average_race_time = round(average_race_time, 2)

# Print the result
print(f"The average race time for {jockey_name} is {average_race_time} seconds.")

The average race time for Brett Prebble is 7517.2 seconds.

In [ ]:
# Question 3: Create a new dataframe that contains rows where horses and their jockeys won first place.
# How much money did first place jockeys win, on average? The money unit is Hong Kong dollars (HKD). Round to two decimal places.

# Create a new Dataframe containing rows where horses and jockeys won first place
first_place_df = df[(df['Final place'] == 1)]

# Calculate the average prize money for first-place jockeys
average_prize_money = first_place_df['Prize money'].mean()

# Round the result to two decimal places
average_prize_money = round(average_prize_money, 2)

# Print the average prize money for first-place jockeys
print(f"The average prize money for first-place jockeys is {average_prize_money} HKD.")

The average prize money for first-place jockeys is 1534781.48 HKD.

In [ ]:
# Question 4: Did winning horses tend to run on dirt or grass surfaces?

# Filter the Dataframe to include only rows where horses won first place
first_place_df = df[df['Final place'] == 1]

# Replace "Gress" with "Grass"
df['Surface'] = df['Surface'].str.replace('Gress', 'Grass', case=False, regex=True)

# Group the filtered Dataframe by the "Surface" column and count the wins for each surface
surface_counts = first_place_df['Surface'].value_counts()

# Determine the surface with the most first-place wins
preferred_surface = surface_counts.idxmax()

# Print the results
print(f"The preferred surface for winning horses is {preferred_surface}.")

The preferred surface for winning horses is Grass.

In [ ]:
# Question 5: What was the fastest race time among horses that ran the 1400 meter race? The units given are in seconds (sometimes, the data is dirty, just assume they are all seconds for now).

#Filter the Dataframe to include only rows where the race distance is 1400 meters
race_1400_df = df[df['Distance'] == 1400]

# Find the fastest race time among the filtered data
fastest_time = race_1400_df['Race time'].min()

# Print the fastest race time in seconds
print(f"The fastest race time for the 1400-meter race is {fastest_time} seconds.")

The fastest race time for the 1400-meter race is 82 seconds.

In [ ]:
# Question 6: What was the slowest race time among Irish horses who ran the 1400 meter race?

# Replace "Irland" with "Ireland"
df['Country'] = df['Country'].str.replace('Irland', 'Ireland', case=False, regex=True)

# Filter the Dataframe to select only Irish horses who ran the 1400 meter race
irish_1400m_races = df[(df['Country'] == 'Ireland') & (df['Distance'] == 1400)]

# Find the slowest race time among the filtered data
slowest_time = irish_1400m_races['Race time'].max()

print(f"The slowest race time among Irish horses who ran the 1400 meter race was {slowest_time} seconds.")

The slowest race time among Irish horses who ran the 1400 meter race was 9291 seconds.

In [ ]:
# Question 7: Which Australian jockey has competed in the most races?

# Filter the 'Country' column down to Australian jockeys
australian_jockeys = df[df['Country'] == 'Australia']

# Group the data by jockey's name and count the number of races
jockey_race_counts = australian_jockeys.groupby('Jockey')['Race Number'].count().reset_index()

# Find the jockey with the most races
most_races_jockey = jockey_race_counts[jockey_race_counts['Race Number'] == jockey_race_counts['Race Number'].max()]

# Display the jockey with the most races
print("The Australian jockey with the most races is:")
print(most_races_jockey)

The Australian jockey with the most races is:
          Jockey  Race Number
31  Joao Moreira          945

In [ ]:
# Question 8: Assume that greater odds indicates a lesser likelihood to win the race.
# According to this data set, which jockey out of Australia, Ireland, or the New Zealand has the least likelihood to win a race, on average (ie. the highest odds)?

# Define a list of countries of interest (Australia, Ireland, New Zealand)
countries_of_interest = ['Australia', 'Ireland', 'New Zealand']

# Filter the dataset to include only jockeys from the specified countries
filtered_jockeys = df[df['Country'].isin(countries_of_interest)]

# Group the data by jockey's name and calculate the average odds
jockey_avg_odds = filtered_jockeys.groupby('Jockey')['Odds'].mean().reset_index()

# Find the jockey with the highest average odds (least likelihood to win)
least_likely_jockey = jockey_avg_odds[jockey_avg_odds['Odds'] == jockey_avg_odds['Odds'].max()]

# Display the jockey with the least likelihood to win on average
print("The jockey from Australia, Ireland, or New Zealand with the least likelihood to win on average is:")
print(least_likely_jockey)

The jockey from Australia, Ireland, or New Zealand with the least likelihood to win on average is:
   Jockey   Odds
24  H Lam  316.5

In [ ]:
df

,Dato,Track,Race Number,Distance,Surface,Prize money,Starting position,Jockey,Jockey weight,Country,...,TrainerName,Race time,Path,Final place,FGrating,Odds,RaceType,HorseId,JockeyId,TrainerID
0,03.09.2017,Sha Tin,10,1400,Grass,1310000,6,K C Leung,52,Sverige,...,CH Yip,8338,2,9,110,22,Handicap,1736,8656,6687
1,16.09.2017,Sha Tin,10,1400,Grass,1310000,14,C Y Ho,52,Sverige,...,CH Yip,8156,3,4,124,48,Handicap,1736,8659,6687
2,14.10.2017,Sha Tin,10,1400,Grass,1310000,8,C Y Ho,52,Sverige,...,CH Yip,8236,1,6,118,11,Handicap,1736,8659,6687
3,11.11.2017,Sha Tin,9,1600,Grass,1310000,13,Brett Prebble,54,Sverige,...,CH Yip,9653,0,8,107,11,Handicap,1736,8453,6687
4,26.11.2017,Sha Tin,9,1600,Grass,1310000,9,C Y Ho,52,Sverige,...,CH Yip,9417,0,3,123,40,Handicap,1736,8659,6687
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27003,14.06.2020,Sha Tin,11,1200,Grass,1450000,6,A Hamelin,59,Australia,...,WY So,7087,1,9,104,25,Handicap,29038,9111,6683
27004,21.06.2020,Sha Tin,2,1200,Grass,967000,7,K C Leung,57,Australia,...,KL Man,6991,2,5,110,124,Handicap,29056,8656,6693
27005,21.06.2020,Sha Tin,4,1200,Grass,967000,6,Blake Shinn,57,Australia,...,P O'Sullivan,6949,0,3,114,88,Handicap,29057,8778,6691
27006,21.06.2020,Sha Tin,5,1200,Grass,967000,14,Joao Moreira,57,New Zealand,...,AS Cruz,7008,2,7,109,22,Handicap,29058,8443,6684
27007,21.06.2020,Sha Tin,11,1200,Grass,1450000,7,C Schofield,55,New Zealand,...,WY So,6951,2,9,118,55,Handicap,29059,8655,6683

In [ ]:
print(df['Horse age'])

0        7
1        7
2        7
3        7
4        7
        ..
27003    3
27004    3
27005    3
27006    3
27007    4
Name: Horse age, Length: 27008, dtype: int64

In [ ]:
# Question 9: Of all horses age 10 or above, what is the horse ID of the one that has the best average race time (ie. the smallest)?

# Filter the dataset to include only horses aged 10 or above
older_horses = df[df['Horse age'] >= 10]

# Group the data by horse ID and calculate the average race time
horse_avg_race_time = older_horses.groupby('HorseId')['Race time'].mean().reset_index()

# Find the horse with the smallest average race time
best_avg_time_horse = horse_avg_race_time[horse_avg_race_time['Race time'] == horse_avg_race_time['Race time'].min()]

# Display the horse ID with the best average race time
print("The horse ID of the horse aged 10 or above with the best average race time is:")
print(best_avg_time_horse)

The horse ID of the horse aged 10 or above with the best average race time is:
   HorseId  Race time
3    22206     4388.0

In [ ]:
# Question 10: Which country won the most races (first place) where the prize money was over $2,000,000?

# Filter the dataset to include only races with prize money over $2,000,000
high_prize_races = df[df['Prize money'] > 2000000]

# Filter the dataset to include only races where the position is '1' (first place)
first_place_wins = high_prize_races[high_prize_races['Final place'] == 1]

# Group the data by country and count the number of first-place wins
country_wins_count = first_place_wins['Country'].value_counts().reset_index()

# Rename the columns for clarity
country_wins_count.columns = ['Country', 'Number_of_First_Place_Wins']

# Find the country with the most first-place wins
most_winning_country = country_wins_count[country_wins_count['Number_of_First_Place_Wins'] == country_wins_count['Number_of_First_Place_Wins'].max()]

# Display the country that won the most races with prize money over $2,000,000
print("The country that won the most races (first place) with prize money over $2,000,000 is:")
print(most_winning_country)

The country that won the most races (first place) with prize money over $2,000,000 is:
     Country  Number_of_First_Place_Wins
0  Australia                          87